package com.monstermind.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room Entity: Represents a saved memory in the local SQLite database.
 *
 * Fields:
 * - id: Unique identifier (auto-generated by Room)
 * - imagePath: Local file system path to the saved image (e.g., /data/data/com.monstermind/...)
 * - extractedText: Text extracted from the image via ML Kit OCR
 * - category: Categorized type (Shopping, Travel, Work, Education, Gaming, Events, Notes, Other)
 * - source: Original source/app name (default: "Unknown source")
 * - createdAt: Timestamp (milliseconds since epoch) when memory was saved
 *
 * All data is stored locally on the device. No cloud synchronization.
 *
 * Example:
 * Memory(
 *   imagePath = "/data/data/com.monstermind/files/concert_1234.jpg",
 *   extractedText = "SUNBURN ARENA\nBENGALURU\n25 OCTOBER 2026",
 *   category = "Events",
 *   source = "Unknown source",
 *   createdAt = 1694920800000L
 * )
 */
@Entity(tableName = "memories")
data class Memory(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,

    val imagePath: String,                          // Local file path to image
    val extractedText: String,                      // OCR result from ML Kit
    val category: String,                           // Classification category
    val source: String = "Unknown source",          // Source app (for future use)
    val createdAt: Long = System.currentTimeMillis() // Creation timestamp
)

/**
 * UI model for memory search results.
 * Includes relevance scoring and matched text for display in lists.
 *
 * Used to show search results ranked by relevance.
 */
data class MemorySearchResult(
    val memory: Memory,
    val relevanceScore: Float,  // 0.0 to 1.0, higher = more relevant
    val matchedText: String     // The text snippet that matched the query
)

/**
 * Constants for memory categories.
 * Initially keyword-based, can be replaced with ML model later (Green Light).
 */
object MemoryCategory {
    const val SHOPPING = "Shopping"
    const val TRAVEL = "Travel"
    const val WORK = "Work"
    const val EDUCATION = "Education"
    const val GAMING = "Gaming"
    const val EVENTS = "Events"
    const val NOTES = "Notes"
    const val OTHER = "Other"

    val all = listOf(SHOPPING, TRAVEL, WORK, EDUCATION, GAMING, EVENTS, NOTES, OTHER)

    fun getEmoji(category: String): String = when (category) {
        SHOPPING -> "🛍️"
        TRAVEL -> "✈️"
        WORK -> "💼"
        EDUCATION -> "📚"
        GAMING -> "🎮"
        EVENTS -> "🎉"
        NOTES -> "📝"
        else -> "📌"
    }
}